---

- hosts: dev
  become: yes

  tasks:
  - name: copying do
    copy: src=/apps/ansible.d/mip_scripts/pas/pro-dopas dest=/usr/util/ mode=755 backup=yes force=yes
    
  - name: copying sh
    copy: src=/apps/ansible.d/mip_scripts/pas/pro-shpas dest=/usr/util/ mode=755 backup=yes force=yes

  - name: copying st
    copy: src=/apps/ansible.d/mip_scripts/pas/pro-stpas dest=/usr/util/ mode=755 backup=yes force=yes
  
  - name: copying qr
    copy: src=/apps/ansible.d/mip_scripts/pas/pro-qrpas dest=/usr/util/ mode=755 backup=yes force=yes
