---
- hosts: mat-lnx1
  become: yes
  gather_facts: true

  tasks:
  - name: Reboot initiated by Ansible for kernel updates
    reboot:
      connect_timeout: 5
      reboot_timeout: 300
      pre_reboot_delay: 0
      post_reboot_delay: 30
      test_command: uptime
