---

- hosts: dev
  become: yes

  tasks:
  - name: copying pasant.zip file
    copy: src=/apps/ansible.d/mip_scripts/pas/pasant.zip dest=/apps/pas122
    
  - name: copying pasant compile 
    copy: src=/apps/ansible.d/managed-scripts/compile-pasant dest=/tmp mode=755

  - name: copying pasant compile 
    shell: sh /tmp/compile-pasant > /tmp/compile-pasant.log
    
  - name: remove temp scripts
    file:  state=absent path=/tmp/compile-pasant /tmp/compile-pasant.log
  
  - name: remove log files
    file:  state=absent path=/tmp/compile-pasant.log
   
   
  
  
