---
- hosts: self
  become: yes
  gather_facts: true

  tasks:
  - name: Apply OS patch updates ( dnf/yum)
    yum: name="*" state=latest

  - name: Rebooting the server
    command: shutdown -r +1 "!!! MIP TechOps IS BUSY WITH SERVER MAINTENANCE !!!"
